"""initial_schema

Revision ID: e161cc9d3830
Revises: 
Create Date: 2026-08-05 05:12:12.062823
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e161cc9d3830'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
